import Head from 'next/head'
// import Navbar from './components/Navbar'
// import Fnav from './components/floralnavbar'
import styles from '../styles/Home.module.css'
// import fnav from './components/floralnavbar'
// import Flonav from './components/flosec'
import Resp from "./components/responsive"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NavBr-Next.JS/Tailwinds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Resp/>
      
    </div>
  )
}
